services:
  - type: web
    name: elevate360-landing
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: elevate360-db
          property: connectionString

databases:
  - name: elevate360-db
    databaseName: elevate360
    user: elevate360_user
    plan: free